server:
  port: 5000 # Elastic Beanstalk expects for Spring Boot Java apps to be deployed on port 5000...

spring:
  application:
    name: spring-boot-poc
  h2:
    console:
      enabled: true
      path: /h2
    url:
    driver-class-name:
    username:
    password:

  logging:
    level:
      org:
        hibernate: INFO
        SQL: DEBUG
        cache: DEBUG
        stat:
          DEBUG

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: validate

management:
  endpoints:
    web:
      exposure:
        include: "*"

