server:
  port: 5000 # Elastic Beanstalk expects for Spring Boot Java apps to be deployed on port 5000...

spring:
  application:
    name: spring-boot-poc
  datasource:
    url: jdbc:postgresql://jb-revature-projects.cidhmnbmwuma.us-east-2.rds.amazonaws.com:5432/postgres?currentSchema=Project_Two
    username: james_bialon
    password: revature

  logging:
    level:
      org:
        hibernate: INFO
        SQL: DEBUG
        cache: DEBUG
        stat: DEBUG

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: validate

management:
  endpoints:
    web:
      exposure:
        include: "*"

